scope: patroni
namespace: /service/

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true
            parameters:
            
    postgresql:
      use_pg_rewind: true

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host replication all all md5
    - host all all all md5

consul:
  scheme: http

postgresql:
    data_dir: /data/patroni
    bin_dir: /usr/lib/postgresql/13/bin
    pgpass: /tmp/pgpass
    parameters:
        unix_socket_directories: '.'
        log_checkpoints: 'on'
        log_duration: 'on'
        log_hostname: 'off'
        log_line_prefix: '[postgres] %m %h %s %u %d %x %e: '
        log_lock_waits: 'off'
        log_statement: 'ddl'
        log_temp_files: '0'
        log_timezone: 'UTC'
        log_parser_stats: 'off'
        log_planner_stats: 'off'
        log_executor_stats: 'off'
        log_statement_stats: 'off'

log:
  level: INFO
  format: '[patroni] %(asctime)s %(levelname)s: %(message)s '

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false

     docker run -d -P --net=host -e PATRONI_API_CONNECT_PORT=8008 -e REPLICATION_NAME=replicator -e REPLICATION_PASS=replpass -e SU_NAME=postgres -e SU_PASS=supass -e POSTGRES_APP_ROLE_PASS=appass -e PATRONI_CONSUL_URL=http://192.168.2.23:8500 -e IP_ADDR=192.168.2.11 patroni8

     docker run -d -p 5434:5432 -p 8009:8091 -v /patroni2:/data/patroni -e PATRONI_API_CONNECT_PORT=8091 -e REPLICATION_NAME=replicator -e REPLICATION_PASS=replpass -e SU_NAME=postgres -e SU_PASS=supass -e POSTGRES_APP_ROLE_PASS=appass -e PATRONI_CONSUL_URL=http://192.168.2.23:8500 tv1n94/patroni-otus


     docker run -d -p 5433:5432 -p 8008:8091  -e PATRONI_API_CONNECT_PORT=8091 -e REPLICATION_NAME=replicator -e REPLICATION_PASS=replpass -e SU_NAME=postgres -e SU_PASS=supass -e POSTGRES_APP_ROLE_PASS=appass -e PATRONI_CONSUL_URL=http://192.168.2.23:8500 tv1n94/patroni-otus

     docker run -d -p 5434:5432 -p 8009:8091  -e PATRONI_API_CONNECT_PORT=8091 -e REPLICATION_NAME=replicator -e REPLICATION_PASS=replpass -e SU_NAME=postgres -e SU_PASS=supass -e POSTGRES_APP_ROLE_PASS=appass -e PATRONI_CONSUL_URL=http://192.168.2.23:8500 tv1n94/patroni-otus


     docker run -d -p 5434:5432 -p 8009:8091 -v /patroni:/data/patroni -e IP_ADDR=$(hostname -i) -e PATRONI_API_CONNECT_PORT=8091 -e REPLICATION_NAME=replicator -e REPLICATION_PASS=replpass -e SU_NAME=postgres -e SU_PASS=supass -e POSTGRES_APP_ROLE_PASS=appass -e PATRONI_CONSUL_URL=http://192.168.2.23:8500 tv1n94/patroni-test

-v /patroni:/data/patroni